name: Android Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Set up Android SDK Command-line Tools
      run: |
        mkdir -p $ANDROID_HOME/cmdline-tools
        cd $ANDROID_HOME/cmdline-tools
        curl -sSL https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -o cmdline-tools.zip
        unzip cmdline-tools.zip
        mv cmdline-tools latest
        echo "$ANDROID_HOME/cmdline-tools/latest/bin" >> $GITHUB_PATH

    - name: Accept Licenses and Install Emulator
      run: |
        yes | sdkmanager --licenses
        sdkmanager "platform-tools" "platforms;android-33" "emulator" "system-images;android-33;google_apis;x86_64"

    - name: Create and Start Emulator
      run: |
        echo "no" | avdmanager create avd -n testAVD -k "system-images;android-33;google_apis;x86_64" --device "pixel"
        $ANDROID_HOME/emulator/emulator -avd testAVD -no-snapshot -no-window -no-audio -gpu swiftshader_indirect &
        adb wait-for-device
        adb shell settings put global window_animation_scale 0 &
        adb shell settings put global transition_animation_scale 0 &
        adb shell settings put global animator_duration_scale 0 &

    - name: Make gradlew executable
      run: chmod +x gradlew
      working-directory: ./LoginTestApp
    
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./LoginTestApp

    - name: Build App
      run: ./gradlew assemble
      working-directory: ./LoginTestApp

    - name: Run Unit Tests
      run: ./gradlew test
      working-directory: ./LoginTestApp

    - name: Run Instrumented Tests
      run: ./gradlew connectedCheck
      working-directory: ./LoginTestApp


