name: Android Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Make gradlew executable
      run: chmod +x gradlew
      working-directory: ./LoginTestApp
    
    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./LoginTestApp

    - name: Build App
      run: ./gradlew assemble
      working-directory: ./LoginTestApp

    - name: Run Unit Tests
      run: ./gradlew test
      working-directory: ./LoginTestApp
    
    - name: Install Android SDK components
      run: |
        sdkmanager "platforms;android-33" "system-images;android-33;google_apis;x86_64" "emulator"

    - name: Create AVD
      run: echo "no" | avdmanager create avd -n test -k "system-images;android-33;google_apis;x86_64" --device "pixel"

    - name: Start emulator
      run: |
        nohup emulator -avd test -no-window -no-audio &
        adb wait-for-device
        adb shell input keyevent 82


    - name: Run Instrumented Tests
      run: ./gradlew connectedCheck
      working-directory: ./LoginTestApp


