name: Android Instrumented Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  instrumented-tests:
    name: Run UI tests on emulator
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create emulator
        run: |
          echo "y" | sdkmanager "system-images;android-30;google_apis;x86"
          sdkmanager --install "emulator"
          export ANDROID_HOME=$ANDROID_SDK_ROOT
          export PATH=$ANDROID_HOME/emulator:$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
          avdmanager create avd -n test -k "system-images;android-30;google_apis;x86" --device "pixel"
          nohup emulator -avd test -no-snapshot -no-window -no-audio -no-boot-anim &
          timeout 300s adb wait-for-device
          adb shell input keyevent 82

      - name: Grant permissions to gradlew
        run: chmod +x ./gradlew

      - name: Run instrumented tests
        run: ./gradlew connectedDebugAndroidTest
