name: Android Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      ANDROID_SDK_ROOT: $HOME/android-sdk

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install Android SDK & Create AVD
      run: |
        sudo apt-get update
        sudo apt-get install -y unzip wget

        mkdir -p $ANDROID_SDK_ROOT/cmdline-tools
        cd $ANDROID_SDK_ROOT/cmdline-tools

        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d latest

        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH

        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT --licenses
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --sdk_root=$ANDROID_SDK_ROOT \
          "platform-tools" \
          "emulator" \
          "platforms;android-30" \
          "system-images;android-30;google_apis;x86_64" \
          "build-tools;30.0.3"

        echo "y" | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/avdmanager create avd -n test_avd -k "system-images;android-30;google_apis;x86_64" --device "pixel"

    - name: Start Android Emulator
      run: |
        export PATH=$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/platform-tools:$PATH
        nohup $ANDROID_SDK_ROOT/emulator/emulator -avd test_avd -no-window -no-audio -gpu off &
        $ANDROID_SDK_ROOT/platform-tools/adb wait-for-device
        sleep 30

    - name: Make gradlew executable
      run: chmod +x gradlew
      working-directory: ./LoginTestApp

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./LoginTestApp

    - name: Run Unit Tests
      run: ./gradlew test
      working-directory: ./LoginTestApp

    - name: Run Instrumented Tests
      run: ./gradlew connectedCheck
      working-directory: ./LoginTestApp

