name: Android Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'   
        distribution: 'temurin'

    - name: Configure environment
      run: |
        echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
        echo "$ANDROID_SDK_ROOT/emulator" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/tools" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/tools/bin" >> $GITHUB_PATH
        echo "$ANDROID_SDK_ROOT/platform-tools" >> $GITHUB_PATH

    - name: Make gradlew executable
      run: chmod +x gradlew
      working-directory: ./LoginTestApp

    - name: Build with Gradle
      run: ./gradlew build
      working-directory: ./LoginTestApp

    - name: Run Unit Tests
      run: ./gradlew test
      working-directory: ./LoginTestApp

    - name: Start Android Emulator
      run: |
        echo "Starting Android Emulator..."
        nohup $HOME/android-sdk/emulator/emulator -avd test_avd -no-window -no-audio -gpu off &
        # Esperar que el emulador arranque
        $HOME/android-sdk/platform-tools/adb wait-for-device
        # Aceptar los términos de la licencia
        $HOME/android-sdk/platform-tools/adb shell input keyevent 82
        sleep 60  # Espera 1 minuto para asegurarse de que el emulador está listo
      working-directory: ./LoginTestApp

    - name: Run Instrumented Tests
      run: ./gradlew connectedCheck
      working-directory: ./LoginTestApp
