name: Android Instrumented Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  instrumented-tests:
    name: Run UI tests on emulator
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Accept Android licenses
        run: |
          mkdir -p ~/.android
          touch ~/.android/repositories.cfg
          yes | sdkmanager --licenses || true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 'latest'
          accept-android-sdk-licenses: true

      - name: Install Android packages
        run: |
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platform-tools" "emulator"
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "platforms;android-30"
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "system-images;android-30;google_apis;x86_64"
          $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --install "build-tools;30.0.3"

      - name: Configure environment
        run: |
          echo "ANDROID_HOME=$ANDROID_SDK_ROOT" >> $GITHUB_ENV
          echo "$ANDROID_SDK_ROOT/emulator:$ANDROID_SDK_ROOT/tools:$ANDROID_SDK_ROOT/tools/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH" >> $GITHUB_ENV

      - name: Create and start emulator
        run: |
          echo "no" | avdmanager create avd --force \
            --name test \
            --package "system-images;android-30;google_apis;x86_64" \
            --device "pixel" \
            --tag "google_apis" \
            --abi "x86_64"
          
          $ANDROID_SDK_ROOT/emulator/emulator -avd test \
            -no-audio \
            -no-window \
            -no-snapshot \
            -gpu swiftshader_indirect \
            -no-boot-anim \
            -memory 2048 \
            -partition-size 2048 &
          
          $ANDROID_SDK_ROOT/platform-tools/adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
          
          $ANDROID_SDK_ROOT/platform-tools/adb devices
          $ANDROID_SDK_ROOT/platform-tools/adb shell getprop

      - name: Grant permissions to gradlew
        run: chmod +x ./gradlew

      - name: Run instrumented tests
        run: |
          ./gradlew connectedDebugAndroidTest \
            --stacktrace \
            --info \
            --no-daemon \
            --max-workers 2

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            app/build/reports/androidTests/connected/
            app/build/outputs/androidTest-results/connected/